application:
  env:
    name: dev

pom:
  version: @project.version@ # need lombok

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: "info, health, loggers, env"
      base-path: /actuator

  endpoint:
    health:
      show-details: always


spring:
  # config:
    # import: optional:file:/app/config/external-config.yml
  datasource:
    url: jdbc:mysql://34.39.2.90:6033/demo_cloud_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: cloud_order
    password: ENC(OJh4XTaWz1beLRY/1cM4Xa6IP/mrKgx2CdVRysJl+BZ/+7eHswcEzQWFF1PR/Hhl)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifeTime: 30000
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      org:
        hibernate:
          envers:
            audit_strategy: org.hibernate.envers.strategy.internal.ValidityAuditStrategy
            audit_strategy_validity_store_revend_timestamp: true

jasypt:
  encryptor:
    # algorithm of encryption
    algorithm: PBEWITHHMACSHA512ANDAES_256
    # salt for encryption
    # how to avoid to expose the salt in the code?
    # https://blog.csdn.net/qq_26878363/article/details/103731173
    password: jaspyt_password


external-custom-config1-path: /app/config/external-config.properties
external-custom-config2-path: /app/config/config2/external-config2.properties

logging:
  level:
    root: INFO
  file: logs/myapp.log